sudo: false
language: python

python:
    - "3.6"

env:
    - PROJECT_DOMAIN=localhost:8000 SECRET_KEY=TRAVIS-SEKRET

install:
    - make install-test

script:
    - make test-coverage

after_success:
    - pip install codecov
    - codecov
